function Cmat = C_func(in1,in2)
%C_FUNC
%    CMAT = C_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Aug-2020 13:50:39

Mf = in2(:,2);
ls = in2(:,6);
lt = in2(:,5);
rfx = in2(:,11);
rfy = in2(:,10);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = lt+rfy;
t3 = -lt;
t5 = (x2.*pi)./1.8e+2;
t4 = ls+t3;
t6 = cos(t5);
t7 = sin(t5);
t8 = rfx.*t6;
t9 = t2.*t7;
t10 = t8+t9;
Cmat = reshape([-Mf.*t4.*t10.*x4,Mf.*t4.*t10.*x3,-Mf.*t4.*t10.*(x3+x4),0.0],[2,2]);
