function Cmat = C_func(in1,in2)
%C_FUNC
%    CMAT = C_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Aug-2020 11:20:46

Mf = in2(:,2);
ls = in2(:,6);
lt = in2(:,5);
rfx = in2(:,11);
rfy = in2(:,10);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = cos(x2);
t3 = sin(x2);
t4 = lt+rfy;
t6 = -lt;
t5 = rfx.*t2;
t7 = t3.*t4;
t8 = ls+t6;
t9 = t5+t7;
Cmat = reshape([-Mf.*t8.*t9.*x4,Mf.*t8.*t9.*x3,-Mf.*t8.*t9.*(x3+x4),0.0],[2,2]);
