function G = G_func(in1,in2)
%G_FUNC
%    G = G_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Aug-2020 11:20:47

Mf = in2(:,2);
Ms = in2(:,1);
g = in2(:,13);
ls = in2(:,6);
lt = in2(:,5);
rfx = in2(:,11);
rfy = in2(:,10);
rs = in2(:,9);
x1 = in1(1,:);
x2 = in1(2,:);
t2 = lt+rfy;
t3 = x1+x2;
t4 = cos(t3);
t5 = sin(t3);
t6 = Mf.*rfx.*t4;
t7 = Mf.*t2.*t5;
G = [g.*(t6+t7+sin(x1).*(Mf.*ls-Mf.*lt+Ms.*rs));g.*(t6+t7)];
