function G = G_func(in1,in2)
%G_FUNC
%    G = G_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Aug-2020 13:50:39

Mf = in2(:,2);
Ms = in2(:,1);
g = in2(:,13);
ls = in2(:,6);
lt = in2(:,5);
rfx = in2(:,11);
rfy = in2(:,10);
rs = in2(:,9);
x1 = in1(1,:);
x2 = in1(2,:);
t2 = lt+rfy;
t3 = x1+x2;
t4 = (t3.*pi)./1.8e+2;
t5 = cos(t4);
t6 = sin(t4);
t7 = Mf.*rfx.*t5;
t8 = Mf.*t2.*t6;
G = [g.*(t7+t8+sin((x1.*pi)./1.8e+2).*(Mf.*ls-Mf.*lt+Ms.*rs));g.*(t7+t8)];
