function JC = J_C_func(in1,in2)
%J_C_FUNC
%    JC = J_C_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Aug-2020 11:21:06

lc = in2(:,7);
ls = in2(:,6);
lt = in2(:,5);
x2 = in1(2,:);
t2 = -lt;
t3 = ls+t2;
JC = reshape([lc+lt+t3.*cos(x2),-t3.*sin(x2),0.0,0.0,0.0,1.0,lc+lt,0.0,0.0,0.0,0.0,1.0],[6,2]);
