function JacobLDot = J_dot_L_func(in1,in2)
%J_DOT_L_FUNC
%    JACOBLDOT = J_DOT_L_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Aug-2020 11:20:47

COPfx = in2(:,12);
la = in2(:,8);
ls = in2(:,6);
lt = in2(:,5);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = cos(x1);
t3 = cos(x2);
t4 = sin(x1);
t5 = sin(x2);
t6 = x1+x2;
t7 = COPfx.^2;
t8 = la.^2;
t11 = -lt;
t9 = cos(t6);
t10 = sin(t6);
t17 = ls+t11;
t12 = COPfx.*t9;
t13 = COPfx.*t10;
t14 = la.*t9;
t15 = la.*t10;
t16 = lt.*t10;
t20 = t2.*t17;
t21 = t4.*t17;
t22 = t5.*t17;
t23 = la.*t3.*t17;
t18 = lt.*t14;
t19 = -t13;
t24 = t16+t22;
t27 = t12+t15+t21;
t25 = COPfx.*t24;
t28 = t27.^2;
t29 = lt+t14+t19+t20;
t26 = -t25;
t30 = t29.^2;
t31 = t7+t8+t18+t23+t26;
t32 = t28+t30;
t33 = 1.0./t32.^(3.0./2.0);
JacobLDot = [t11.*t29.*t33.*(t31.*x4+x3.*(t7+t8+t23.*2.0+lt.*(t14+t19+COPfx.*t5.*2.0)+lt.*t20+t17.^2-COPfx.*ls.*t5.*2.0)),-t31.*t33.*(x4.*(t18+t23-ls.*lt.*2.0+t11.*t13+ls.^2+lt.^2.*2.0+lt.*t2.*(ls.*2.0-lt.*2.0)-COPfx.*ls.*t5+COPfx.*lt.*t5)+lt.*t29.*x3)];
