function JacobLDot = J_dot_L_func(in1,in2)
%J_DOT_L_FUNC
%    JACOBLDOT = J_DOT_L_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Aug-2020 13:50:40

COPfx = in2(:,12);
la = in2(:,8);
ls = in2(:,6);
lt = in2(:,5);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = x1+x2;
t3 = COPfx.^2;
t4 = la.^2;
t5 = -lt;
t7 = (x1.*pi)./1.8e+2;
t8 = (x2.*pi)./1.8e+2;
t6 = ls+t5;
t9 = cos(t7);
t10 = cos(t8);
t11 = sin(t7);
t12 = sin(t8);
t13 = (t2.*pi)./1.8e+2;
t14 = cos(t13);
t15 = sin(t13);
t23 = t6.*t9;
t24 = t6.*t11;
t25 = t6.*t12;
t26 = la.*t6.*t10;
t16 = COPfx.*t14;
t17 = COPfx.*t15;
t18 = la.*t14;
t19 = la.*t15;
t20 = lt.*t15;
t21 = lt.*t18;
t22 = -t17;
t27 = t20+t25;
t30 = t16+t19+t24;
t28 = COPfx.*t27;
t31 = t30.^2;
t32 = lt+t18+t22+t23;
t29 = -t28;
t33 = t32.^2;
t34 = t3+t4+t21+t26+t29;
t35 = t31+t33;
t36 = 1.0./t35.^(3.0./2.0);
JacobLDot = [t5.*t32.*t36.*(t34.*x4+x3.*(t3+t4+t26.*2.0+lt.*(t18+t22+COPfx.*t12.*2.0)+lt.*t23+t6.^2-COPfx.*ls.*t12.*2.0)),-t34.*t36.*(x4.*(t21+t26-ls.*lt.*2.0+t5.*t17+ls.^2+lt.^2.*2.0+lt.*t9.*(ls.*2.0-lt.*2.0)-COPfx.*ls.*t12+COPfx.*lt.*t12)+lt.*t32.*x3)];
