function JacobL = J_L_func(in1,in2)
%J_L_FUNC
%    JACOBL = J_L_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Aug-2020 11:20:47

COPfx = in2(:,12);
la = in2(:,8);
ls = in2(:,6);
lt = in2(:,5);
x1 = in1(1,:);
x2 = in1(2,:);
t2 = cos(x1);
t3 = sin(x1);
t4 = x1+x2;
t7 = -lt;
t5 = cos(t4);
t6 = sin(t4);
t12 = ls+t7;
t8 = COPfx.*t5;
t9 = COPfx.*t6;
t10 = la.*t5;
t11 = la.*t6;
t14 = t2.*t12;
t15 = t3.*t12;
t13 = -t9;
t16 = t8+t11+t15;
t17 = t16.^2;
t18 = lt+t10+t13+t14;
t19 = t18.^2;
t20 = t17+t19;
t21 = 1.0./sqrt(t20);
JacobL = [t7.*t16.*t21,-t21.*(la.*(lt.*t6+t12.*sin(x2))+lt.*t8+COPfx.*t12.*cos(x2))];
