function Jacobtheta = J_Theta_func(in1,in2)
%J_THETA_FUNC
%    JACOBTHETA = J_THETA_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Aug-2020 13:50:42

COPfx = in2(:,12);
la = in2(:,8);
ls = in2(:,6);
lt = in2(:,5);
x1 = in1(1,:);
x2 = in1(2,:);
t2 = x1+x2;
t3 = lt.*2.0;
t4 = -lt;
t5 = lt./2.0;
t7 = (x1.*pi)./1.8e+2;
t6 = ls+t4;
t8 = cos(t7);
t9 = sin(t7);
t10 = (t2.*pi)./1.8e+2;
t11 = cos(t10);
t12 = sin(t10);
t23 = t6.*t8;
t24 = t6.*t9;
t13 = COPfx.*t11;
t14 = COPfx.*t12;
t15 = la.*t11;
t16 = la.*t12;
t26 = t23.*2.0;
t27 = t23./2.0;
t17 = t14.*2.0;
t18 = t15.*2.0;
t19 = -t14;
t21 = t14./2.0;
t22 = t15./2.0;
t28 = t13+t16;
t20 = -t17;
t25 = -t21;
t29 = t24+t28;
t31 = lt+t15+t19+t23;
t30 = t29.^2;
t32 = t31.^2;
t33 = t3+t18+t20+t26;
t34 = t5+t22+t25+t27;
t35 = t30+t32;
t36 = 1.0./t35;
t37 = 1.0./sqrt(t35);
t38 = t37.^3;
t39 = t32.*t36;
t40 = -t39;
t41 = t40+1.0;
t42 = 1.0./sqrt(t41);
Jacobtheta = [-t42.*(t29.*t37-t34.*t38.*(t29.*t33-t29.*(t18+t20+t26))),-t42.*(t28.*t37-t34.*t38.*(t28.*t33+t29.*(t17-t18)))];
