function Jacobtheta = J_Theta_func(in1,in2)
%J_THETA_FUNC
%    JACOBTHETA = J_THETA_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Aug-2020 11:20:49

COPfx = in2(:,12);
la = in2(:,8);
ls = in2(:,6);
lt = in2(:,5);
x1 = in1(1,:);
x2 = in1(2,:);
t2 = cos(x1);
t3 = sin(x1);
t4 = x1+x2;
t5 = lt.*2.0;
t8 = -lt;
t9 = lt./2.0;
t6 = cos(t4);
t7 = sin(t4);
t14 = ls+t8;
t10 = COPfx.*t6;
t11 = COPfx.*t7;
t12 = la.*t6;
t13 = la.*t7;
t21 = t2.*t14;
t22 = t3.*t14;
t15 = t11.*2.0;
t16 = t12.*2.0;
t17 = -t11;
t19 = t11./2.0;
t20 = t12./2.0;
t24 = t21.*2.0;
t25 = t21./2.0;
t26 = t10+t13;
t18 = -t15;
t23 = -t19;
t27 = t22+t26;
t29 = lt+t12+t17+t21;
t28 = t27.^2;
t30 = t29.^2;
t31 = t5+t16+t18+t24;
t32 = t9+t20+t23+t25;
t33 = t28+t30;
t34 = 1.0./t33;
t35 = 1.0./sqrt(t33);
t36 = t35.^3;
t37 = t30.*t34;
t38 = -t37;
t39 = t38+1.0;
t40 = 1.0./sqrt(t39);
Jacobtheta = [-t40.*(t27.*t35-t32.*t36.*(t27.*t31-t27.*(t16+t18+t24))),-t40.*(t26.*t35-t32.*t36.*(t26.*t31+t27.*(t15-t16)))];
