function L = L_func(in1,in2)
%L_FUNC
%    L = L_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Aug-2020 13:50:39

COPfx = in2(:,12);
la = in2(:,8);
ls = in2(:,6);
lt = in2(:,5);
x1 = in1(1,:);
x2 = in1(2,:);
t2 = x1+x2;
t3 = -lt;
t5 = (x1.*pi)./1.8e+2;
t4 = ls+t3;
t6 = (t2.*pi)./1.8e+2;
t7 = cos(t6);
t8 = sin(t6);
L = sqrt((lt-COPfx.*t8+la.*t7+t4.*cos(t5)).^2+(COPfx.*t7+la.*t8+t4.*sin(t5)).^2);
