function L = L_func(in1,in2)
%L_FUNC
%    L = L_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Aug-2020 11:20:47

COPfx = in2(:,12);
la = in2(:,8);
ls = in2(:,6);
lt = in2(:,5);
x1 = in1(1,:);
x2 = in1(2,:);
t2 = x1+x2;
t5 = -lt;
t3 = cos(t2);
t4 = sin(t2);
t6 = ls+t5;
L = sqrt((lt-COPfx.*t4+la.*t3+t6.*cos(x1)).^2+(COPfx.*t3+la.*t4+t6.*sin(x1)).^2);
