function M = M_func(in1,in2)
%M_FUNC
%    M = M_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Aug-2020 13:50:38

Ifz = in2(:,4);
Isz = in2(:,3);
Mf = in2(:,2);
Ms = in2(:,1);
ls = in2(:,6);
lt = in2(:,5);
rfx = in2(:,11);
rfy = in2(:,10);
rs = in2(:,9);
x2 = in1(2,:);
t2 = lt+rfy;
t3 = -lt;
t5 = (x2.*pi)./1.8e+2;
t4 = ls+t3;
t6 = cos(t5);
t7 = sin(t5);
t8 = t4.*t6;
t9 = t4.*t7;
t10 = -t9;
t11 = t2+t8;
t12 = rfx+t10;
t14 = Mf.*t2.*t11;
t13 = Mf.*rfx.*t12;
t15 = Ifz+t13+t14;
M = reshape([Ifz+Isz+Ms.*rs.^2+Mf.*t11.^2+Mf.*t12.^2,t15,t15,Ifz+Mf.*rfx.^2+Mf.*t2.^2],[2,2]);
