function M = M_func(in1,in2)
%M_FUNC
%    M = M_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Aug-2020 11:20:46

Ifz = in2(:,4);
Isz = in2(:,3);
Mf = in2(:,2);
Ms = in2(:,1);
ls = in2(:,6);
lt = in2(:,5);
rfx = in2(:,11);
rfy = in2(:,10);
rs = in2(:,9);
x2 = in1(2,:);
t2 = cos(x2);
t3 = sin(x2);
t4 = lt+rfy;
t5 = -lt;
t6 = ls+t5;
t7 = t2.*t6;
t8 = t3.*t6;
t9 = -t8;
t10 = t4+t7;
t11 = rfx+t9;
t13 = Mf.*t4.*t10;
t12 = Mf.*rfx.*t11;
t14 = Ifz+t12+t13;
M = reshape([Ifz+Isz+Ms.*rs.^2+Mf.*t10.^2+Mf.*t11.^2,t14,t14,Ifz+Mf.*rfx.^2+Mf.*t4.^2],[2,2]);
