function THETA = Theta_func(in1,in2)
%THETA_FUNC
%    THETA = THETA_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Aug-2020 13:50:40

COPfx = in2(:,12);
la = in2(:,8);
ls = in2(:,6);
lt = in2(:,5);
x1 = in1(1,:);
x2 = in1(2,:);
t2 = x1+x2;
t3 = -lt;
t5 = (x1.*pi)./1.8e+2;
t4 = ls+t3;
t6 = cos(t5);
t7 = (t2.*pi)./1.8e+2;
t8 = cos(t7);
t9 = sin(t7);
t13 = t4.*t6;
t10 = COPfx.*t9;
t11 = la.*t8;
t12 = -t10;
t14 = lt+t11+t12+t13;
THETA = (pi.*1.8e+2-acos(t14.*1.0./sqrt((COPfx.*t8+la.*t9+t4.*sin(t5)).^2+t14.^2)).*1.8e+2)./pi;
