function THETA = Theta_func(in1,in2)
%THETA_FUNC
%    THETA = THETA_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Aug-2020 11:20:48

COPfx = in2(:,12);
la = in2(:,8);
ls = in2(:,6);
lt = in2(:,5);
x1 = in1(1,:);
x2 = in1(2,:);
t2 = cos(x1);
t3 = x1+x2;
t6 = -lt;
t4 = cos(t3);
t5 = sin(t3);
t9 = ls+t6;
t7 = COPfx.*t5;
t8 = la.*t4;
t11 = t2.*t9;
t10 = -t7;
t12 = lt+t8+t10+t11;
THETA = pi-acos(t12.*1.0./sqrt(t12.^2+(COPfx.*t4+la.*t5+t9.*sin(x1)).^2));
