function Ke = KE_func(in1,in2)
%KE_FUNC
%    KE = KE_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Jan-2020 14:19:42

%Prosthesis file. Needs state and parameters as inputs
Mf = in2(:,2);
Ms = in2(:,1);
la = in2(:,5);
lf = in2(:,6);
ls = in2(:,4);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
t2 = cos(x3);
t3 = cos(x4);
t4 = sin(x3);
t5 = sin(x4);
t6 = x3+x4;
t13 = la./2.0;
t7 = t2.^2;
t8 = t4.^2;
t9 = ls.*t3;
t10 = cos(t6);
t11 = sin(t6);
t12 = ls.*t5.*4.0;
t19 = (Ms.*ls.*t4)./2.0;
t23 = (Ms.*ls.*t2)./2.0;
t14 = t10.^2;
t15 = t11.^2;
t16 = -t12;
t17 = Ms.*t7;
t18 = Ms.*t8;
t24 = Mf.*t10.*t13;
t25 = (Mf.*lf.*t10)./4.0;
t26 = t9+t13;
t27 = Mf.*t11.*t13;
t28 = (Mf.*lf.*t11)./4.0;
t20 = lf+t16;
t21 = Mf.*t14;
t22 = Mf.*t15;
t29 = -t28;
t31 = Mf.*t10.*t26;
t32 = Mf.*t11.*t26;
t33 = Mf.*t13.*t26;
t37 = t25+t27;
t30 = (Mf.*lf.*t20)./1.6e+1;
t34 = (Mf.*t10.*t20)./4.0;
t35 = (Mf.*t11.*t20)./4.0;
t38 = t24+t29;
t39 = t17+t18+t21+t22;
t36 = -t35;
t40 = t30+t33;
t41 = t19+t32+t34;
t42 = t23+t31+t36;
Ke = (x5.*(t39.*x5+t38.*x8+t42.*x7))./2.0+(x6.*(t37.*x8+t39.*x6+t41.*x7))./2.0+(x8.*(x8.*((Mf.*la.^2)./4.0+(Mf.*lf.^2)./1.6e+1)+t37.*x6+t38.*x5+t40.*x7))./2.0+(x7.*(t41.*x6+t42.*x5+t40.*x8+x7.*((Ms.*ls.^2)./4.0+(Mf.*t20.^2)./1.6e+1+Mf.*t26.^2)))./2.0;
end