function lJacob = Spring_Jacobian_func(in1,in2)
%SPRING_JACOBIAN_FUNC
%    LJACOB = SPRING_JACOBIAN_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Jan-2020 14:19:45

%Prosthesis file. Needs state and parameters as inputs
la = in2(:,5);
lf = in2(:,6);
ls = in2(:,4);
lt = in2(:,3);
px = in2(:,7);
py = in2(:,8);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = cos(x3);
t3 = sin(x3);
t4 = lf.*px;
t5 = lt+py;
t6 = x3+x4;
t7 = la.*2.0;
t8 = ls.*2.0;
t9 = ls.*t2;
t10 = cos(t6);
t11 = ls.*t3;
t12 = sin(t6);
t13 = lf.*t5;
t17 = lt+t7+t8;
t14 = lf.*t10;
t15 = lf.*t12;
t16 = -t11;
t20 = px.*t17;
t22 = t5.*t17;
t23 = t10.*t17;
t24 = t12.*t17;
t18 = -t14;
t19 = -t15;
t21 = -t20;
t25 = -t23;
t26 = px+t16+t18+t24;
t27 = t5+t9+t19+t25;
t28 = t26.^2;
t29 = t27.^2;
t30 = t28+t29;
t31 = 1.0./sqrt(t30);
lJacob = [0.0;0.0;-t31.*(-t12.*(t4+t22)+t10.*(t13+t21)+px.*t9+t5.*t11);t31.*(t12.*(t4+t22+lf.*t16+t9.*t17)-t10.*(t13+t21+lf.*t9+t11.*t17))];
end