% knee_joint_vel = zeros(size(time));
% ankle_joint_vel = knee_joint_vel;
% for i = 1:length(time)
%     [~,~, ~, ~, ~, ~,...
%         ~, ~, ~,~, ~, ~, ~, ~, ...
%         ~,~, ~, ~, ~,~,~,~,~,knee_joint_vel(i),ankle_joint_vel(i),~]...
% = SLIP_KPBC(0, knee_joint_pos(I(i)), ankle_joint_pos(I(i)), ...
%             time(i), dt(I(i)), ...
%             0, 0, 0, ...
%             0, 0, 0,...
%             0, 0, 0, 0, 0, 0,...
%             vel_filter_coeff(I(i)), 0,...
%             0, 0, 0,0, 0, ...
%             0, 0, 0, 0, 0,...
%             0, 0, 0, 0,...
%             0,...
%             0, 0, 0,...
%             0);
%         
%         derp=1;
% end

hip_vel = zeros(size(time));
%ankle_joint_vel = knee_joint_vel;
for i = 1:length(time)
    [~,~, ~, ~, ~, ~,...
        ~, ~, ~,~, ~, ~, ~, ~, ...
        ~,~, ~, ~, ~,~,~,~,~,~,~,hip_vel(i)]...
= SLIP_KPBC(IMU_pitch(I(i)), knee_joint_pos(I(i)), ankle_joint_pos(I(i)), ...
            time(i), dt(I(i)), ...
            0, 0, 0, ...
            0, 0, 0,...
            0, 0, 0, 0, 0, 0,...
            vel_filter_coeff(I(i)), 0,...
            0, 0, 0,0, 0, ...
            0, 0, 0, 0, 0,...
            0, 0, 0, 0,...
            0,...
            0, 0, 0,...
            0);
        
        derp=1;
end

hip_vel(abs(hip_vel)>200) = nan;