%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: Z:\Member Folders\Mark Yeatman\Codes\Matlab\Leg2_Implementation\PilotExperiments\Data\Ankle PushOffEditTest 03-02-20 04 17 40 PM.dat
%
% Auto-generated by MATLAB on 03-Mar-2020 11:44:52

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 33);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["load_cell_z_moment", "kp_knee", "kd_knee", "kp_ankle", "kd_ankle", "ankle_des_in", "knee_des_in", "vel_filter_coeff", "IMU_filter_coeff", "SLIP_ON", "lt1", "k", "d", "L0", "KPBC_ON", "pbc_gain_ankle", "pbc_gain_knee", "M", "Eref", "knee_stop_low", "knee_stop_high", "ankle_stop_low", "ankle_stop_high", "max_torque", "hip_thresh_st", "hip_vel_thresh_st", "dumb3", "F_thresh", "hip_vel", "dumb2", "ankle_joint_vel", "knee_joint_vel", "Command_State"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("Z:\Member Folders\Mark Yeatman\Codes\Matlab\Leg2_Implementation\PilotExperiments\Data\Ankle TestB 12-31-03 06 00 00 PM.dat", opts);

%% Convert to output type
load_cell_z_moment = tbl.load_cell_z_moment;
kp_knee = tbl.kp_knee;
kd_knee = tbl.kd_knee;
kp_ankle = tbl.kp_ankle;
kd_ankle = tbl.kd_ankle;
ankle_des_in = tbl.ankle_des_in;
knee_des_in = tbl.knee_des_in;
vel_filter_coeff = tbl.vel_filter_coeff;
IMU_filter_coeff = tbl.IMU_filter_coeff;
SLIP_ON = tbl.SLIP_ON;
lt1 = tbl.lt1;
k = tbl.k;
d = tbl.d;
L0 = tbl.L0;
KPBC_ON = tbl.KPBC_ON;
pbc_gain_ankle = tbl.pbc_gain_ankle;
pbc_gain_knee = tbl.pbc_gain_knee;
M = tbl.M;
Eref = tbl.Eref;
knee_stop_low = tbl.knee_stop_low;
knee_stop_high = tbl.knee_stop_high;
ankle_stop_low = tbl.ankle_stop_low;
ankle_stop_high = tbl.ankle_stop_high;
max_torque = tbl.max_torque;
hip_thresh_st = tbl.hip_thresh_st;
hip_vel_thresh_st = tbl.hip_vel_thresh_st;
dumb3 = tbl.dumb3;
F_thresh = tbl.F_thresh;
hip_vel = tbl.hip_vel;
dumb2 = tbl.dumb2;
ankle_joint_vel = tbl.ankle_joint_vel;
knee_joint_vel = tbl.knee_joint_vel;
Command_State = tbl.Command_State;

%% Clear temporary variables
clear opts tbl

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: Z:\Member Folders\Mark Yeatman\Codes\Matlab\Leg2_Implementation\PilotExperiments\Data\Knee PushOffEditTest 03-02-20 04 17 40 PM.dat
%
% Auto-generated by MATLAB on 03-Mar-2020 11:45:46

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 33);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Knee_torque_command", "Ankle_torque_command", "delta_L", "hip_pos", "Esys", "Esys_int_out", "U_lin_spring_k", "U_lin_spring_a", "U_lin_damp_k", "U_lin_damp_a", "U_stop_k", "U_stop_a", "U_pbc_k", "U_pbc_a", "knee_des_out", "ankle_des_out", "foot_contact", "stance", "swing", "phase_out", "IMU_LIVE", "StanceGain", "SwingGain", "IMU_pitch", "knee_joint_pos", "ankle_joint_pos", "time_in", "dt", "load_cell_x_force", "load_cell_y_force", "load_cell_z_force", "load_cell_x_moment", "load_cell_y_moment"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tb2 = readtable("Z:\Member Folders\Mark Yeatman\Codes\Matlab\Leg2_Implementation\PilotExperiments\Data\Knee TestB 12-31-03 06 00 00 PM.dat", opts);

%% Convert to output type
Knee_torque_command = tb2.Knee_torque_command;
Ankle_torque_command = tb2.Ankle_torque_command;
delta_L = tb2.delta_L;
hip_pos = tb2.hip_pos;
Esys = tb2.Esys;
Esys_int_out = tb2.Esys_int_out;
U_lin_spring_k = tb2.U_lin_spring_k;
U_lin_spring_a = tb2.U_lin_spring_a;
U_lin_damp_k = tb2.U_lin_damp_k;
U_lin_damp_a = tb2.U_lin_damp_a;
U_stop_k = tb2.U_stop_k;
U_stop_a = tb2.U_stop_a;
U_pbc_k = tb2.U_pbc_k;
U_pbc_a = tb2.U_pbc_a;
knee_des_out = tb2.knee_des_out;
ankle_des_out = tb2.ankle_des_out;
foot_contact = tb2.foot_contact;
stance = tb2.stance;
swing = tb2.swing;
phase_out = tb2.phase_out;
IMU_LIVE = tb2.IMU_LIVE;
StanceGain = tb2.StanceGain;
SwingGain = tb2.SwingGain;
IMU_pitch = tb2.IMU_pitch;
knee_joint_pos = tb2.knee_joint_pos;
ankle_joint_pos = tb2.ankle_joint_pos;
time_in = tb2.time_in;
dt = tb2.dt;
load_cell_x_force = tb2.load_cell_x_force;
load_cell_y_force = tb2.load_cell_y_force;
load_cell_z_force = tb2.load_cell_z_force;
load_cell_x_moment = tb2.load_cell_x_moment;
load_cell_y_moment = tb2.load_cell_y_moment;

%% Clear temporary variables
clear opts tb2